-- auto-generated definition
create table event
(
    id                 serial                   not null
        constraint event_pk
            primary key,
    name               text                     not null,
    url                text                     not null,
    date_from          timestamp with time zone not null,
    date_to            timestamp with time zone,
    type               text                     not null,
    location_city      text,
    location_country   text,
    image              text,
    free               boolean,
    price_from         text,
    price_to           text,
    description        text,
    contact_info_email text,
    vendor_name        text,
    vendor_link        text,
    twitter_link       text,
    status             text,
    facebook_link      text,
    youtube_link       text,
    linkedin_link      text,
    keywords           text,
    location_address   text,
    slug               text
);

comment on table event is 'Contains all IT events';

alter table event
    owner to postgres;

create unique index event_id_uindex
    on event (id);


-- auto-generated definition
create table search_event
(
    id          serial                              not null
        constraint search_term_pk
            primary key,
    timestamp   timestamp default CURRENT_TIMESTAMP not null,
    search_term text                                not null
);

alter table search_event
    owner to postgres;

create unique index search_term_id_uindex
    on search_event (id);



INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (429, '.NET Summit', 'https://dotnetsummit.by', '2020-08-07 00:00:00.000000', '2020-08-09 00:00:00.000000', 'Online Conference', null, null, 'https://static.tildacdn.com/tild6364-3035-4262-b130-346331373638/Asset_38.svg', false, 'EUR 65', null, 'The 4th community driven .NET conference dedicated to practical experience of solving business challenges with .NET and technical challenges in .NET application', 'roman@eventspace.by', 'Space_; .NET User Group - Minsk', 'https://techevents.space; https://www.facebook.com/groups/dotnet.minsk/', 'https://twitter.com/dotnetby', 'Inactive', 'https://www.facebook.com/DotNetSummitBelarus/', 'https://www.youtube.com/channel/UCX5g8IOR_tw1OkiFAzAZHaA/playlists?view=50&sort=dd&shelf_id=9', null, '.NET', null, 'net-summit');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (430, 'UX Conference August', 'https://www.nngroup.com/training/august/', '2020-08-10 00:00:00.000000', '2020-08-21 00:00:00.000000', 'Online Conference', null, null, 'https://media.nngroup.com/static/img/logo-817x388.png', false, 'USD 791', 'USD 6401', 'Full-day live virtual courses about UX best practices, proven methods, and hands-on exercises led by NN/g experts and world-class invited speakers. Enjoy the comfort and convenience of your own office or home as you learn.

Choose from 40 different UX topics. All courses are 100% live interaction - no pre-recorded content.
2-way video conferencing for class discussions and Q&A with instructors
Hands-on activities with collaboration tools with industry peers 
Membership in the NN/g UX Slack Community, where you can connect with other digital professionals. (Permanent membership included with your registration.)
Earn a UX Certificate online, at your own pace', 'events@nngroup.com', 'Nielsen Norman Group', 'https://www.nngroup.com', 'https://twitter.com/nngroup', 'Inactive', null, null, null, 'UX,Mobile,Design', null, 'ux-conference-august');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (432, 'RustConf', 'https://rustconf.com', '2020-08-20 00:00:00.000000', null, 'Online Conference', null, null, null, false, 'USD 5', 'USD 99', 'RustConf gathers developers from around the world to learn and share with one another ... and this time it''s virtual.', 'events@tilde.io', 'Tilde', 'https://www.tilde.io', null, 'Inactive', null, null, null, 'Rust', null, 'rustconf');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (433, 'Kafka Summit 2020', 'https://events.kafka-summit.org/2020', '2020-08-24 00:00:00.000000', '2020-08-25 00:00:00.000000', 'Online Conference', null, null, null, null, 'TBC', null, 'As event streaming platforms become central to data strategies, companies both small and large are re-thinking their architecture with real-time context at the forefront. Monoliths are evolving into Microservices.  Datacenters are moving to the cloud. What was once a ‘batch’ mindset is quickly being replaced with stream processing as the demands of the business impose more and more real-time requirements on developers and architects.', null, 'Confluent, Inc', 'https://www.confluent.io/?utm_medium=sem&utm_source=google&utm_campaign=ch.sem_br.brand_tp.prs_tgt.confluent-brand_mt.xct_rgn.emea_lng.eng_dv.all&utm_term=confluent&creative=&device=c&placement=&gclid=Cj0KCQjwupD4BRD4ARIsABJMmZ_nprjxGQ2mFXdjHQ8fjEN94fTyktgGA8VaPj9c2kt0u8xnhbxE258aAqtpEALw_wcB', 'https://twitter.com/ConfluentInc', 'Inactive', 'https://www.facebook.com/confluentinc/', null, 'https://www.linkedin.com/company/confluent/', 'Microservices,Cloud', null, 'kafka-summit-2020');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (435, 'Devops Fusion', 'https://www.devops-fusion.com/en/', '2020-08-26 00:00:00.000000', null, 'Online Conference', null, null, 'https://www.devops-fusion.com/wp-content/themes/std_dof_wp_theme/images/logo-flat-devops.svg', false, 'CHF 630', 'CHF 900.00', '(New) content on demand: switch between talks in real time & get access to recordings after the conference 
Easy networking: group and private chats, as well as instant matchmaking make it easier to meet new people and make new connections 
Live Q&A: submit questions during talks while following the live stream 
Share with a friend: your ticket provides you and a colleague (!) access to the conference', 'info@devops-fusion.com', null, null, 'https://twitter.com/DevOpsFusion', 'Inactive', 'https://www.facebook.com/DevOpsFusion', null, 'https://www.linkedin.com/company/devops-fusion/', 'DevSecOps,German', null, 'devops-fusion');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (436, 'Fighting AI Bias With High-Quality Training Data', 'https://www.re-work.co/events/webinar-data-quality-2020', '2020-08-26 00:00:00.000000', null, 'Webinar', null, null, null, true, 'USD 0', 'USD 25', 'Our events bring together the latest technology advancements as well as practical examples to apply AI to solve challenges in business and society. Our unique mix of academia and industry enables you to meet with AI pioneers at the forefront of research, as well as exploring real-world case studies to discover the business value of AI.
', 'hello@re-work.co', 'RE•WORK  LTD', 'https://www.re-work.co', 'https://twitter.com/teamrework', 'Inactive', 'https://www.facebook.com/teamrework', null, 'https://www.linkedin.com/company/re-work/', 'ML,AL', null, 'fighting-ai-bias-with-high-quality-training-data');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (437, 'You Gotta Love Frontend', 'https://lithuania.yglfconf.com', '2020-08-24 00:00:00.000000', '2020-08-28 00:00:00.000000', 'Online Conference', null, null, null, true, null, null, 'For the second time, YGLF is coming to Lithuania. With a growing industry, supported by a lively and passionate community of developers, it’s time YGLF brings some of its magic to Vilnius. Set to take place in the city center, in a freshly renovated, and somewhat hipsterish venue, we plan to bring you big names with irresistible talks and a whole lot of fun!

YGLF is a series of community events built by developers for developers. It''s a non-profit conference aimed at delivering high-quality content on the hottest topics that cutting edge front-end developers need to know. Bringing in internationally recognized speakers and attendees, with the young and vibrant atmosphere of the front-end community, YGLF creates a buzzling bustle of software engineers from around the globe. Check out photos from YGLF Lithuania 2019. ', 'lt@yougottalovefrontend.com', null, null, 'https://twitter.com/yglf_lt', 'Inactive', 'https://www.facebook.com/yglflt/', 'https://www.youtube.com/channel/UCU-fOxx_kT5OARG0KiksiCA', null, 'Frontend', null, 'you-gotta-love-frontend');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (434, 'RenderATL', 'https://www.renderatl.com', '2020-09-13 00:00:00.000000', '2020-09-16 00:00:00.000000', 'Conference', 'Atlants', 'USA', 'https://files.makeswift.com/RmlsZTpmMGRkNDI0NS1lYWQ2LTQ3MDQtYWI2My04Y2MyMmVkOGRiNmY=/logo.svg', false, 'USD 300', 'USD 1302', 'RenderATL is the first major React conference in the Southern United States. Conceived by a team of passionate React engineers who''re looking to help drive more diversity, inclusion, and, accessibility into the React ecosystem.

With these goals in mind, what better place to hold the conference than the South''s very own melting pot – Atlanta!

', null, null, null, 'https://twitter.com/renderATL', 'Inactive', 'https://www.facebook.com/renderatl/', null, null, 'React ', '84 Northyards Blvd NW,
Atlanta,
GA 30313', 'renderatl');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (454, 'ActivityPub Conf', 'https://conf.activitypub.rocks', '2020-10-02 00:00:00.000000', '2020-10-05 00:00:00.000000', 'Online Conference', null, null, null, true, null, null, 'A conference about the present and future of ActivityPub, the world’s leading federated social web standard.

The 2020 virtual conference will include
pre-recorded talks with live question and answer sessions
birds of a feather sessions
lightning round talks
a hackathon that follows the conference.', 'activitypubconf@riseup.net', null, null, null, 'Active', null, null, null, 'ActivityPub, Web', null, 'activitypub-conf');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (440, 'Devopsdays Zürich', 'https://devopsdays.org/events/2020-zurich/welcome/', '2020-09-01 00:00:00.000000', '2020-09-30 00:00:00.000000', 'Online Conference', null, null, 'https://d33wubrfki0l68.cloudfront.net/fba174b19270a1db8de8910558e38b4fdabc4dcc/5515d/img/devopsdays-brain.png', true, null, null, 'Every Tuesday evening in September 2020 we will hold the online DevOpsTuesDays; No registration needed for DevOpsTuesDays Zürich 2020', 'zurich@devopsdays.org', null, null, 'https://twitter.com/devopsdays?lang=en', 'Inactive', null, null, null, 'DevOps', null, 'devopsdays-zurich');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (441, 'Ai4 2020', 'https://ai4.io', '2020-08-18 00:00:00.000000', '2020-08-20 00:00:00.000000', 'Online Conference', null, null, null, true, 'USD 0', 'USD 295', 'Over three days, Ai4 2020 brings together business leaders and data practitioners to facilitate the adoption of artificial intelligence and machine learning technology. Join us at industry’s most impactful AI event. With a use-case oriented approach to content, we deliver actionable insights from those working on the frontlines of AI in the enterprise. We provide a common framework for thinking about what AI means to each industry and deliver content that progresses understanding at any stage of an organization’s AI journey. Welcome to our community!', 'jessica@ai4.io', null, null, 'https://twitter.com/Ai4Conferences', 'Inactive', 'https://www.facebook.com/Ai4.io/?ref=ai4', null, 'https://www.linkedin.com/company/ai4/', 'AL,ML', null, 'ai4-2020');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (442, 'SpringOne', 'https://springone.io', '2020-09-02 00:00:00.000000', '2020-09-03 00:00:00.000000', 'Online Conference', null, null, null, true, null, null, 'The same cloud native conference you know and love, in an all-virtual format. See your old pals and make new ones. Watch hundreds of breakout sessions. And catch your favorite speakers, all from the comfort of your living room or repurposed kitchen nook (and likely theirs).

It’s all online. It’s all free. It’s all (still) happening.', 'springone@vmware.com', 'VMware, Inc', 'https://www.vmware.com', 'https://twitter.com/springone', 'Inactive', null, null, null, 'Cloud,Cloud Native', null, 'springone');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (443, 'CascadiaJS', 'https://2020.cascadiajs.com', '2020-09-01 00:00:00.000000', '2020-09-02 00:00:00.000000', 'Online Conference', null, null, 'https://2020.cascadiajs.com/_static/images/icon-green-d9097c0543.svg', false, 'USD 99', 'USD 149', 'CascadiaJS has always been about bringing together an amazing group of web developers from across the Pacific Northwest (and beyond) to hear great talks, meet amazing people, and have fun.
When you buy a ticket, you get:
 Access to the live stream of talks
 Access to speaker Q&A
 Access to the Job Fair on August 31st
 Access to both evening social events (Karaoke Night & Game Night)
 A Goodie Box shipped to you that will include:
 CascadiaJS hoodie
 Stickers
 Extra surprises!', 'info@cascadiajs.com', null, null, 'https://twitter.com/cascadiajs', 'Inactive', null, null, null, '3-D,API,Bundling,CSS,Canvas,Databases,Debugging,DevOps,Dweb,ES Modules,Gifs,Git,HardwareI,PFS,IoT,JAM Stack,JavaScript,Monorepo,React,SVG,TypeScript,UI,Node,GraphQL', null, 'cascadiajs');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (444, 'ProductCamp', 'https://productcamp.pl', '2020-09-02 00:00:00.000000', '2020-09-04 00:00:00.000000', 'Online Conference', null, null, 'https://productcamp.pl/wp-content/themes/productcamp.pl/assets/logo-light@2x.png?v=2', false, 'USD 99', null, 'ProductCamp 2020 Online is a 3-day event for Product Managers, Owners, Product Designers, Researchers, Growth Hackers and all professionals who discover, conceive, manage and make digital products better.', 'event@productcamp.pl', null, null, 'https://twitter.com/productcamppl', 'Inactive', 'https://www.facebook.com/productcamppl/', 'https://www.youtube.com/channel/UCD1xGZC-q6wa-tAjD9KRAdA/videos', 'https://www.linkedin.com/company/productcamp', 'Product Managers,Owners,Product Designers,Researchers,Growth Hackers', null, 'productcamp');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (438, 'try! Swift', 'https://www.tryswift.co/events/2020/nyc/', '2020-08-30 00:00:00.000000', '2020-09-01 00:00:00.000000', 'Conference', 'New York', 'USA', 'https://www.tryswift.co/assets/images/logo_riko_labs_navbar_nyc.png', false, 'TBC', null, 'try! Swift Conference is an international community gathering about the latest advancements in Swift Development. The event is about bringing together talent from all around the world to collaborate and share advanced knowledge and techniques to improve Swift craftsmanship. Coming again to New York City on August 31st & September 1st, with workshops on August 30th!', 'nyc@tryswift.co', 'Natasha The Robot, LLC', 'https://www.natashatherobot.com', 'https://twitter.com/tryswiftnyc', 'Inactive', 'https://www.facebook.com/tryswiftconf/', null, null, 'Swift', '340 W 50th St,
New York,
NY 10019', 'try-swift');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (431, 'Southern Data Science Conference', 'https://www.southerndatascience.com', '2020-08-12 00:00:00.000000', '2020-08-14 00:00:00.000000', 'Conference', 'Atlanta', 'USA', 'https://static.wixstatic.com/media/99c986_064741c97f8a434bae6347c83efc8d8c~mv2.png/v1/fill/w_820,h_462,al_c/99c986_064741c97f8a434bae6347c83efc8d8c~mv2.png', false, 'USD 200', 'USD 550', 'SDSC is a special data science R&D conference that brings experts and researchers from the top data science companies and institutes to present their work and share their best practices in data science. Our Atlanta conference was organized on April 11-12, 2019 with 500+ attendees who represented industry, academia, and government institutions across the US.', null, ' Southern Data Science, LLC', 'https://www.southerndatascience.com', 'https://twitter.com/southerndsc', 'Inactive', 'https://www.facebook.com/southerndatascience/', null, null, 'Data Science,R&D,NLP,Python,AI,Data Analytics,Apache Spark,Spark MLib', '2 Galleria Pkwy SE,
Atlanta,
GA 30339,
United States', 'southern-data-science-conference');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (452, 'Intersection', 'https://www.intersection-conference.eu', '2020-10-01 00:00:00.000000', '2020-10-02 00:00:00.000000', 'Online Conference', null, null, 'https://www.intersection-conference.eu/themes/custom/intersection/templates/svg/logo.svg', false, 'EUR 49', null, 'The coolest DESIGN AND DEVELOPMENT CONFERENCE by Hinto IS BACK! In 2020  edition we will move BEYOND BOUNDARIES, strategically addressing the challenges and opportunities presented by the changing landscape of our industry.

This year, due to the spread of covid-2019, the conference will be held entirely online.', 'intersection@hinto.com', 'HINTO S.R.L. All Rights Reserved', 'https://www.hinto.com/it', 'https://twitter.com/Intersection_eu', 'Active', 'https://www.facebook.com/IntersectionConference/', null, 'https://www.linkedin.com/company/intersection-ux-dev/', 'Design', null, 'intersection');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (453, 'MS Stage', 'https://msstage.com', '2020-10-02 00:00:00.000000', null, 'Online Conference', null, null, 'https://msstage.com/wp-content/uploads/2019/12/MStage_logo.png', true, null, null, 'Make a deep dive into reality and future of Microsoft technology stack – .Net, C#, F#, MS Azure, Cosmos DB, SQL Server, VS Code Spaces and other.
You will be able to join 16 talk.

Communication thru special Slack channel will allow you to interact with speakers, put questions and discuss each topic.

Enjoy full HD quality and professional video editing, that complement informative content.', 'info@msstage.com', 'Code Space', 'https://codespace.com.ua', null, 'Active', null, null, null, '.Net,MS SQL,MS Azure,Cosmos DB', null, 'ms-stage');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (439, 'JavaScript Days - Munish', 'https://javascript-days.de/muenchen/tickets-muenchen/?go=ok', '2020-09-01 00:00:00.000000', '2020-09-04 00:00:00.000000', 'Online Conference', 'Munich', 'Germany', null, false, 'EUR 699', 'EUR 1699', 'At the JavaScript Days, Angular Days, React Days and HTML & CSS Days, a selection of first-class experts will provide you with in-depth information on how to optimally plan JavaScript and HTML-based applications and how to successfully implement them, which strengths and weaknesses the different technologies have or how you can help should choose a suitable architecture. 1-4 September 2020 in Munich & online.', 'ypreuss@sandsmedia.com; cguminski@sandsmedia.com', 'Software & Support Media GmbH', 'https://sandsmedia.com/', 'https://twitter.com/js_days', 'Inactive', 'https://www.facebook.com/JavaScript-Days-340008479422077/', null, null, 'JavaScript,Angular,React, HTML,CSS,German', 'Holiday Inn Munich City Center
Hochstrasse 3,
81669 Munich', 'javascript-days-munish');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (446, 'International Conference on Data Mining and Software Engineering', 'https://dmse2020.org', '2020-09-26 00:00:00.000000', '2020-09-27 00:00:00.000000', 'Conference', 'Copenhagen', 'Denmark', null, false, 'TBC', null, 'International Conference on Data Mining and Software Engineering (DMSE 2020) will provide an excellent international forum for sharing knowledge and results in theory, methodology and applications of Data mining and Software Engineering. The goal of this conference is to bring together researchers and practitioners from academia and industry to focus on understanding Data mining and modern software engineering concepts and establishing new collaborations in these areas.

Authors are solicited to contribute to the conference by submitting articles that illustrate research results, projects, surveying works and industrial experiences that describe significant advances in the areas of data mining and software engineering.', 'dmse@dmse2020.org or dmsesecretary@gmail.com', null, null, 'https://twitter.com/AIRCCFP', 'Active', null, null, 'https://www.youtube.com/channel/UCzkuYvuKuNCIc3jbE52IeZg', 'Data Mining,Software Engineering', 'Phoenix Hotel Copenhagen, Bredgade 37,
DK-1260 Copenhagen K,
Copenhagen, Denmark.', 'international-conference-on-data-mining-and-software-engineering');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (447, 'DeveloperWeek Seattle: Cloud Edition', 'https://www.developerweek.com/CloudEdition/', '2020-09-28 00:00:00.000000', '2020-09-29 00:00:00.000000', 'Conference', 'Seattle', 'USA', 'https://www.developerweek.com/CloudEdition/wp-content/uploads/2019/12/DWSEA_1Line_ColorWhiteGreen.png', false, 'USD 0', 'USD 395', 'DeveloperWeek Seattle: Cloud Edition is Seattle’s premiere cloud computing conference, where 800+ cloud engineers, IT managers, entrepreneurs, and innovators will converge to discover this year’s newest cloud computing innovations! Seattle is already seen by the world as the cloud computing capital, hosting many of the world’s largest cloud providers. Come learn about technologies including:', null, null, null, 'https://twitter.com/DevWeekSEA', 'Active', 'https://www.facebook.com/DeveloperWeek-Seattle-550019218818144/', null, 'https://www.linkedin.com/showcase/developerweek/', 'Cloud', 'Grand Hyatt Seattle
721 Pine Street
Seattle, Washington', 'developerweek-seattle-cloud-edition');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (448, 'enterJS', 'https://enterjs.de', '2020-09-28 00:00:00.000000', '2020-10-01 00:00:00.000000', 'Conference', 'Darmstadt', 'Germany', 'https://enterjs.de/common/images/konferenzen/enterjs.svg', false, 'EUR 750', 'EUR 1700', 'The conference for enterprise JavaScript
EnterJS will open its gates for the seventh time in 2020 and offers developers a comprehensive view of the JavaScript-based enterprise world. The focus is not only on the latest trends around the JavaScript programming language itself, but also on the frameworks and tools that are part of the tools of every JavaScript developer. Of course, the conference also takes a look at the latest technologies and frameworks. Always with the aim of being able to assess whether it is worth using them in your own team.

With all technology topics, enterJS never loses sight of its use in the corporate context. It highlights stumbling blocks from the migration of old applications to the integration of new technologies and the scaling of applications. We talk about DevOps and cloud, design and user experience, accessibility and testing. Speakers report on their own experiences and lessons learned from real projects and show what is really possible.', 'info@enterjs.de', 'heise Developer', 'https://www.heise.de/developer/', 'https://twitter.com/enterjsconf', 'Active', null, null, null, 'German,Java Script', null, 'enterjs');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (449, 'SQLbits', 'https://sqlbits.com', '2020-09-29 00:00:00.000000', '2020-10-03 00:00:00.000000', 'Conference', 'London', 'UK', 'https://sqlbits.com/images/sqlbits/SQLBitsLogo.png', false, 'GBP 349', 'GBP 1499', 'Network, develop and share your data knowledge at THE conference for leading data professionals
SQLBits is the largest Microsoft Data Platform conference in Europe. Born out of the hunger to share the latest developments, solutions and best practice, whilst forming a network of data professionals behind some of the most exciting developments on the Microsoft Data Platform.
Now with a new five day format we return to London in 2020, for a marathon of top quality training from global specialists. At a time of change if you want to learn about the new paradigms in data platforms, SQLBits is the place.', 'contactus@sqlbits.com', null, null, 'https://twitter.com/sqlbits', 'Active', 'https://www.facebook.com/SQLBits/', null, 'https://www.linkedin.com/company/sqlbits', 'Microsoft Data Platform', 'ExCeL London
Royal Victoria Dock, 1 Western Gateway, Royal Docks, London E16 1XL', 'sqlbits');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (450, 'TNW Conference', 'https://thenextweb.com/conference', '2020-10-01 00:00:00.000000', '2020-10-02 00:00:00.000000', 'Online Conference', null, null, null, null, null, null, 'Join 25,000 of the world’s brightest minds to explore the role tech will play in our collective future. The 15th edition of our flagship event will bring our global speaker lineup and an immersive digital experience to your living room.', 'conference@thenextweb.com', null, null, 'https://twitter.com/TNWevents', 'Active', 'https://www.facebook.com/TNWEvents', 'https://www.facebook.com/TNWEvents', null, 'Artificial intelligence,Big data,Machine learning', null, 'tnw-conference');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (451, 'Mind the Product', 'https://www.mindtheproduct.com/mtpcon/london/', '2020-10-01 00:00:00.000000', '2020-10-02 00:00:00.000000', 'Conference', 'London', 'UK', 'https://3lsqjy1sj7i027fcn749gutj-wpengine.netdna-ssl.com/wp-content/themes/mtp/assets/img/logo@2x.png', false, 'GBP 589', 'GBP 749', 'Every year we bring together product leaders from around the world to explore the intersection of design, technology, and business, inspiring you to build better products.

The conference day itself (Friday, 2nd October 2020) brings together over 1,700 product people for a day of epic talks at the Barbican in London.  We will once more also offer a range of optional deep-dive workshops, and a separate leadership event to bring together the more senior people of our tribe – both happening the day before the conference on Thursday, 1st October 2020.', null, null, null, 'https://twitter.com/MindtheProduct', 'Active', 'https://www.facebook.com/MindTheProduct', null, 'https://www.linkedin.com/company/mind-the-product/', 'Product management ', 'Silk St, Barbican, London EC2Y 8DS, United Kingdom', 'mind-the-product');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (455, 'nodejsday', 'https://2020.nodejsday.it', '2020-10-02 00:00:00.000000', null, 'Online Conference', null, null, 'https://2020.nodejsday.it/img/themes/nodejsday/nodejsday-logo.svg', false, 'EUR 102.89', 'EUR 295.96', 'Node.js® is a JavaScript runtime built on Chrome''s V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js'' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. nodejsday, previously known as Node.js Italian Conference, it''s an international conference dedicated to Node.js. Started and formerly organized by WEBdeBS is now organized by GrUSP, the organizers of jsday.

', 'info@grusp.org', ' GrUSP ', 'http://www.grusp.org/it/', 'https://twitter.com/nodejsconfit', 'Active', 'https://www.facebook.com/nodejsday/', 'https://www.youtube.com/c/GrUSP', null, 'Node.js,JavaScript', null, 'nodejsday');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (456, 'Interop', 'https://www.interop.com', '2020-10-05 00:00:00.000000', '2020-10-08 00:00:00.000000', 'Online Conference', null, null, 'https://www.interop.com/sites/default/files/Interop_Digital_logo_2020.png', false, 'TBC', null, null, 'interopregistration@informa.com', ' Informa PLC.', 'https://www.informa.com', 'https://twitter.com/interop', 'Active', 'https://www.facebook.com/Interop', 'https://www.youtube.com/channel/UCc9dGgFhBFGTwYkQNTOLV6g', 'https://www.linkedin.com/company/interop-las-vegas/', 'Data,AL,Automation,Cloud,Security,Networks,Infrastructure,Devops', null, 'interop');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (457, '3rd Middle East Banking AI & Analytics Summit', 'https://www.mebankingai.com', '2020-10-05 00:00:00.000000', '2020-10-06 00:00:00.000000', 'Conference', 'Dubai', 'the United Arab Emirates', 'https://www.mebankingai.com/images/logo/logo.png', false, 'USD 599', 'USD 1799', '3rd Edition Middle East Banking AI & Analytics Summit the only AI & Analytics Summit in GCC which brings together 300+ senior-level executives & decision-makers from the Banking and Financial Services sector along with all that''s top of mind for those in Artificial Intelligence, RPA, Machine Learning, Big Data & Analytics', 'info@mebankingai.com', null, null, 'https://twitter.com/LetsTalkB2B', 'Active', 'https://www.facebook.com/LetsTalkeventseries/', null, 'https://www.linkedin.com/company/letstalkbiz/', 'Banking AL,Analytics,ML', '31166 - Sheikh Mohammed bin Rashid Blvd - Downtown Dubai - Dubai - United Arab Emirates', '3rd-middle-east-banking-ai-analytics-summit');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (458, 'UXDX', 'https://uxdx.com', '2020-10-06 00:00:00.000000', '2020-10-09 00:00:00.000000', 'Online Conference', null, null, 'https://uxdx.com/static/logo-518ae5bc8ae83c41592c020a426d7eb2.svg', false, 'EUR 200', 'EUR 425', 'Bridging the gap between Product, UX, Design and Dev', null, 'Socially Motivated Ltd', 'https://www.solocheck.ie/Irish-Company/Socially-Motivated-Limited-547304', 'https://twitter.com/uxdxconf?lang=en', 'Active', 'https://www.facebook.com/uxdxconf/', 'https://www.youtube.com/channel/UCbHlDYI3bkUa1vx_qdJ8nbg', 'https://www.linkedin.com/company/uxdx/', 'Product,UX,Design,Dev', null, 'uxdx');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (459, 'Future Developer Summit', 'https://www.futuredeveloper.io', '2020-10-06 00:00:00.000000', '2020-10-07 00:00:00.000000', 'Online Conference', null, null, null, true, null, null, 'Future Developer Summit is aiming at creating a community event where developer marketing and relations leaders debate best practices, learn and design better developer strategies.
 Special edition
While 2020 is challenging industries, business and individuals significantly, the Future Developer Summit is determined to turn this into an enhanced learning opportunity for the developer marketing and relations community.
Traditionally invite-only on-site gathering, this year the Summit opens its doors to all developer marketing professionals and enthusiasts for a remote edition of the event!', null, 'SlashData', 'https://www.slashdata.co', 'https://twitter.com/slashdatahq', 'Active', 'https://www.facebook.com/SlashData/', null, 'https://www.linkedin.com/company/slashdata/', 'Developer Marketing,Developer Relations', null, 'future-developer-summit');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (460, 'JAMstack Conf', 'https://jamstackconf.com', '2020-10-06 00:00:00.000000', '2020-10-07 00:00:00.000000', 'Conference', 'San Francisco, CA.', 'USA', null, false, 'TBC', null, 'Jamstack Conf is a two day celebration of the next generation of web apps, where the Jamstack community and ecosystem comes together to learn, connect and create. Attendees range from front end and full stack engineers to web agencies all ready to push the boundaries of tomorrow’s web architecture.', null, 'Netlify', 'https://www.netlify.com', 'https://twitter.com/jamstackconf', 'Active', null, null, null, 'Jamstack', null, 'jamstack-conf');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (461, 'ELixirConf EU', 'https://www.elixirconf.eu', '2020-10-07 00:00:00.000000', '2020-10-08 00:00:00.000000', 'Online Conference', null, null, 'https://www.elixirconf.eu/assets/images/logo.svg', false, 'TBC', null, 'The premiere Elixir conference in Europe
The conference is a melting pot for new ideas and inspired thinking.
It showcases the great work being done with Elixir by individuals and companies alike.
It helps those new to the community find their feet, and welcomes back those who have attended before, to champion and progress the uptake and development of Elixir in Europe. In June, we welcomed over 400 Elixir users from around the world to our first virtual ElixirConf EU event, and this time, we want to make it even bigger!
More information about the virtual event will be available soon. Let’s stay connected!', 'info@elixirconf.eu', 'ElixirConf EU ', 'https://www.elixirconf.eu', 'https://twitter.com/elixirconfeu?lang=en', 'Active', null, 'https://www.youtube.com/watch?v=8xJzHq8ru0M&list=PLvL2NEhYV4ZtoiQC735NjHyPJUS_nmrxy', null, 'Elixir', null, 'elixirconf-eu');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (462, '#Pragma Conference', 'https://www.pragmaconference.com', '2020-10-07 00:00:00.000000', '2020-10-09 00:00:00.000000', 'Conference', 'Bologna', 'Italy', 'https://www.pragmaconference.com/assets/media/pragmaconf_logo.png', false, 'TBC', null, 'The Italian iOS/macOS/watchOS/tvOS Developers Conference', 'info@pragmamark.org', null, null, 'https://twitter.com/pragmamarkorg', 'Active', 'https://www.facebook.com/pragmamark/', 'https://www.youtube.com/user/pragmamark', null, 'iOS,macOS,watchOS,tvOS', 'Via del Pilastro, 2, 40127 Bologna BO, Italy', 'pragma-conference');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (463, 'Spring I/O', 'https://2020.springio.net', '2020-10-08 00:00:00.000000', '2020-10-09 00:00:00.000000', 'Conference', 'Barcelona', 'Spain', 'https://2020.springio.net/images/logo-spring-io.svgg', false, 'EUR 419', 'EUR 479', 'Spring I/O is the leading european conference focused on the Spring Framework ecosystem.
Join us in our 9th edition!', 'info@springio.net', null, null, 'https://twitter.com/spring_io', 'Active', null, 'https://www.youtube.com/channel/UCLMPXsvSrhNPN3i9h-u8PYg/videos', null, 'Spring', 'Fira de Barcelona
Avinguda de la Reina Maria Cristina, s/n, 08004 Barcelona', 'spring-io');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (464, 'TSConf', 'https://tsconf.io', '2020-10-09 00:00:00.000000', null, 'Online Conference', null, null, null, false, 'USD 25', 'USD 39', 'Trying to stay connected to the TypeScript community while maintaining social distance? We’ve got you covered with TSConf 2020 Online! We’re passionate about TypeScript and TSConf strives to be the community experience where we come together to learn, share, and have a good time – regardless of locale!', 'tsconf@sitepen.com', 'sitepen', 'https://www.sitepen.com', 'https://twitter.com/typescriptconf', 'Active', null, null, null, 'TypeScript', null, 'tsconf');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (465, 'TEQnation Conference', 'https://conference.teqnation.com', '2020-10-09 00:00:00.000000', null, 'Conference', 'Utrecht', 'Netherlands', 'https://conference.teqnation.com/wp-content/uploads/2019/02/Teqnation-Event_cmyk_diap.png', false, 'EUR 129.99', 'EUR 179.99', 'The Biggest multitrack Developer Conference of the Netherlands.
At TEQnation you can broaden your knowledge at our hands-on labs, technical sessions, live demonstrations and workshops,
which are all focused on technology of the next era.

TEQnation 2020 will bring more than 1.000 developers and 50+ speakers from all over the world.

Featured topics
AI & ML, IoT & Embedded, Developer Experience, Modern Infrastructure, Security and New & Cool.
Share your passion with like-minded people, improve your skills and have fun in an easy-going atmosphere at TEQnation 2020.', 'rbussenius@reshift.nl', 'Reshift Business Innovation', null, 'https://twitter.com/teqnation2019', 'Active', 'https://www.facebook.com/TEQnation/', null, 'https://www.linkedin.com/company/11480480', 'AI,ML,IoT,Embedded,Developer Experience,Modern Infrastructure,Security', null, 'teqnation-conference');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (466, 'Data Saturday', 'https://datasaturday.nl', '2020-10-10 00:00:00.000000', null, 'Conference', 'Ede', 'Netherlands', 'https://datasaturday.nl/wp-content/uploads/2019/05/pass_new.jpg', false, 'EUR 20', null, 'Data Saturday Holland is the new name for SQL Saturday Holland. Join 750 of your peers to network and enjoy 42 sessions from top speakers from all over the world. The content will focus mainly on the Microsoft Data Platform. Come join us if you want to learn about topics like SQL Server, Azure Datawarehouse, Databricks, Kubernetes, Cosmos DB, Powershell, Data Factory, Power BI, and many more.', null, null, null, 'https://twitter.com/datasaturdaynl', 'Active', null, null, 'https://www.linkedin.com/company/datasaturday/', 'SQL,Azure,Databricks,Kubernetes,Cosmos DB,Powershell,Data Factory,Power BI', 'Pathé Ede

Laan der Verenigde Naties 150

6716 JE Ede

The Netherlands', 'data-saturday');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (467, 'ReactNext', 'https://www.react-next.com', '2020-10-12 00:00:00.000000', null, 'Conference', 'Tel Aviv', 'Israel', 'https://www.react-next.com/wp-content/uploads/2020/06/Menu-Icon.png', false, 'EUR 165', 'EUR 255', 'After a very successful 4 consecutive years, EventHandler brings you the 2020 edition of ReactNext. The all technical conference brings top local and international speakers to share their experiences with over 850 developers in Israel. The conference features advanced topics aimed for experienced developers, team leaders, and consultants. And a great oppurtinuty R&D and product managers to evaluate the business advantages of React.', 'team@react-next.com', 'Event Handler ', 'https://www.eventhandler.co.il', 'https://twitter.com/reactnext?lang=en', 'Active', 'https://www.facebook.com/eventhandlerpro/', 'https://www.youtube.com/channel/UC3BT8hh3yTTYxbLQy_wbk2w', null, 'React', 'InterContinental David Tel Aviv
Kaufmann St 12, Tel Aviv-Yafo, 61501, Israel', 'reactnext');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (468, 'NDC Sydney', 'https://ndcsydney.com', '2020-10-12 00:00:00.000000', '2020-10-16 00:00:00.000000', 'Online Conference', null, null, null, false, 'USD 1590', 'USD 3690', 'Since its start-up in Oslo 2008, the Norwegian Developers Conference (NDC) quickly became one of Europe`s largest conferences for .NET & Agile development. Today NDC Conferences are 5-day events with 2 days of pre-conference workshops and 3 days of conference sessions.
', 'info@ndcconferences.com', null, null, 'https://twitter.com/ndc_conferences', 'Active', 'https://www.facebook.com/ndcconferences', 'https://www.youtube.com/c/ndcconferences', 'https://www.linkedin.com/company/10446421/', '.NET,Agile', null, 'ndc-sydney');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (469, 'MCubed - AI, ML, and analytics conference', 'https://www.mcubed.london', '2020-10-12 00:00:00.000000', '2020-10-14 00:00:00.000000', 'Conference', 'London', 'UK', 'https://www.mcubed.london/wp-content/uploads/2020/02/M320_logo_V3.png', false, 'GBP 600', null, 'MCubed returns to London in 2020 to bring together experts in artificial intelligence, machine learning and data science to help software architects, application developers and data analysts get on the path to a more intelligent future.

For our fourth edition, we are going to change things up a little. Of course our speakers will keep taking you beyond the hype around trendy frameworks and pie in the sky visions. But we''ll also turn the spotlight onto the main issues many enterprises struggle with right now: taking the step from researching ML to actual production.

We''ll make sure you get your most burning questions answered through more interactive sessions, introduce you to new tools and approaches, and help you find people who are in the same boat as you are. Everything to help you put your AI projects on solid footing', null, null, null, 'https://twitter.com/MCubedLondon', 'Active', null, null, null, 'AI,ML,ANALYTICS', 'Broad Sanctuary, Westminster, London SW1P 3EE, United Kingdom', 'mcubed-ai-ml-and-analytics-conference');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (470, 'HashiConf US', 'https://hashiconf.com/digital-october/', '2020-10-12 00:00:00.000000', '2020-10-15 00:00:00.000000', 'Online Conference', null, null, null, true, null, null, 'An online HashiCorp community conference with the same keynotes, technical sessions, product updates, and community connections that you have come to expect from HashiCorp events.', 'hashiconf@hashicorp.com', null, null, 'https://twitter.com/hashicorp', 'Active', 'https://www.facebook.com/HashiCorp/', 'https://www.youtube.com/HashiCorp', 'https://www.linkedin.com/company/hashicorp/', null, null, 'hashiconf-us');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (471, 'API Conference Berlin', 'https://apiconference.net/berlin', '2020-10-12 00:00:00.000000', '2020-10-14 00:00:00.000000', 'Online Conference', 'Berlin', 'Germany ', 'https://apiconference.net/wp-content/uploads/2020/04/APIC_Herbst20_Website_Desktop_Logo_56544_v1.png', false, 'EUR 359', 'EUR 944', 'The Conference for Web APIs,
API Design & Management
October 12 – 14, 2020 | Berlin or Online', null, 'Software & Support Media', 'https://sandsmedia.com/en/home/', 'https://twitter.com/api_conference', 'Active', 'https://www.facebook.com/apiconf/', 'https://www.youtube.com/channel/UCtmmVmkh4D-8V-sHBD_S3TQ', null, 'Web APIs,API Design,Management', 'MARITIM PROARTE HOTEL BERLIN
FRIEDRICHSTRASSE 151,
10117 BERLIN', 'api-conference-berlin');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (472, 'dataMinds Connect', 'https://datamindsconnect.be', '2020-10-13 00:00:00.000000', null, 'Online Conference', null, null, 'https://datamindsconnect.be/wp-content/uploads/2019/03/logo.png', true, null, null, 'dataMinds Connect is the new and improved version of the (former SQLUG.be) SQL Server Days. New and improved, keeping in mind the same core values. 2 days filled with learning, networking and a whole lot of laughs while doing so!

This year will be the 13th edition of the conference, and running for the third time as dataMinds Connect. Aiming to bring together all people with a passion for the Microsoft Data Platform, in all flavours possible, we’re hoping to receive even more people than last year!

Go ahead and clearly mark Tuesday 13th 2020 in your schedule, as this will be a day you don’t want to miss!', null, null, null, 'https://twitter.com/datamindsbe', 'Active', 'https://twitter.com/datamindsbe', null, 'https://www.linkedin.com/company/28651227', 'SQL', null, 'dataminds-connect');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (473, 'SmashingConf', 'https://smashingconf.com/austin-2020', '2020-10-13 00:00:00.000000', '2020-10-14 00:00:00.000000', 'Online Conference', null, null, 'https://d33wubrfki0l68.cloudfront.net/aacda99f06f673547274c3a6edd7ce58232841d0/69a66/images/events/nav/austin-2020.svg', false, 'USD 175', 'USD 225', 'The Smashing Cat is going online, y’all! Meet an inclusive, practical and friendly conference on front-end, design and UX, with CSS/JS techniques, accessibility, performance, privacy, internationalization, designing for mobile, HTML email and real-life case studies. Mark your calendar October 13–14. Jump to the timezones ↬', 'hello@smashingconf.com', null, null, 'https://twitter.com/smashingconf', 'Active', null, null, null, 'Front-end,Design,UX,CSS/JS,HTML', null, 'smashingconf');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (474, 'reactjsday', 'https://2020.reactjsday.it', '2020-10-15 00:00:00.000000', null, 'Online Conference', null, null, 'https://2020.reactjsday.it/img/themes/reactjsday/reactjsday-logo.svg', false, 'EUR 102.90', 'EUR 295.97', 'React.js is the JavaScript library developed by Facebook and Instagram to create fast and reusable user interfaces. Introducing new development paradigms and best practices to the frontend, it has gathered a large and active community of developers. The conference is organized by GrUSP, the organizers of jsday, vueday, and angularday.', 'info@grusp.org', ' GrUSP ', 'http://www.grusp.org/it/', 'https://twitter.com/reactjsday', 'Active', 'https://www.facebook.com/reactjsday/', 'https://www.youtube.com/channel/UCdWnwC8nz_CCFQrmLBrLCVw', null, 'React,JavaScript', null, 'reactjsday');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (475, 'TestBash Netherlands', 'https://www.ministryoftesting.com/events/testbash-netherlands-online-2020', '2020-10-15 00:00:00.000000', '2020-10-16 00:00:00.000000', 'Online Conference', null, null, 'https://d2h1nbmw1jjnl.cloudfront.net/events/images/000/000/171/original/TestBash_NL_Online_2020_DOJO_EVENT.png?1589453428', true, 'GBP 0', 'GBP 249.99', 'From our humble beginnings, we’ve grown into a truly awesome global software testing community! Community is our core; we allow the community to guide us, and co-create everything we make and do with community members. This includes our TestBash software testing conferences and all the software testing content on The Dojo!

', null, null, null, 'https://twitter.com/ministryoftest', 'Active', null, null, 'https://twitter.com/ministryoftest', 'Testing', null, 'testbash-netherlands');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (476, 'PEPR', 'https://www.usenix.org/conference/pepr20', '2020-10-15 00:00:00.000000', '2020-10-16 00:00:00.000000', 'Conference', 'Santa Clara, Ca', 'USA', 'https://www.usenix.org/sites/default/files/styles/neat_conference_menu_logo/public/pepr20_logo_wordmark_white_400x159.png?itok=e5PHFATv', false, 'TBC', null, 'PEPR is focused on designing and building products and systems with privacy and respect for their users and the societies in which they operate. Our goal is to improve the state of the art and practice of building for privacy and respect and to foster a deeply knowledgeable community of both privacy practitioners and researchers who collaborate towards that goal.

After thorough consideration, and with the safety of our attendees, speakers, volunteers, staff, and vendors in mind, we have decided to reschedule the upcoming PEPR ''20 to October 15–16, 2020. It will still take place at the Hyatt Regency Santa Clara in Santa Clara, CA, USA.', 'conference@usenix.org', 'Usenix', 'https://www.usenix.org', 'https://twitter.com/usenix', 'Active', 'https://www.facebook.com/pages/USENIX-Association/124487434386', 'https://www.youtube.com/user/USENIXAssociation', 'https://www.linkedin.com/company/usenix-association/', 'Design', 'Hyatt Regency Santa Clara
5101 Great America Parkway
Santa Clara, CA 95054
USA', 'pepr');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (477, 'All Things Open', 'https://2020.allthingsopen.org', '2020-10-19 00:00:00.000000', '2020-10-20 00:00:00.000000', 'Online Conference', null, null, null, true, 'USD 0', 'USD 129', 'All Things Open is a polyglot technology conference focusing on the tools, processes and people making open source possible. Target audience includes designers, developers, decision makers, entrepreneurs and technologists of all types and skill levels.', null, null, null, null, 'Active', null, null, null, 'Back-End Developer,Big Data,Block Chain,Cloud,Databases,Devops,Front-End Developer,Front-End Engineering,Hardware / IOT,Linux / Infrastructure,Machine Learning,Mobile Developer,Programming Lanuages,Security,UI / UX / Design', null, 'all-things-open');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (478, 'UIArchConf', 'http://uiarchconf.com', '2020-10-19 00:00:00.000000', '2020-10-20 00:00:00.000000', 'Conference', 'New Orleans', 'USA', null, false, 'USD 400', 'USD 1295', 'UIArchConf is a unique conference and training event for those who work as UI Architects, or are looking to become a UI Architect. What''s a UI Architect?

We will explore the various aspects of UI Architecture and the role of the UI Architect, and the massive role a UI architect plays in an organization. From traditional "architect" tasks such as defining coding standards, to UX standardization, ensuring accessibility is a forethought and not an afterthought, the UI Architect wears many hats, and is a leader within their company championing the user interface.

If you are a Design, UX, User Experience, or Front-End developer/engineer, you can benefit both your company and your career by attending UIArchConf. You might already spend some of your time doing the things a UI Architect does! You will learn from your community experts who are currently in this role, or are playing a similar role.', null, 'ConnectEvents', 'https://connectevents.io', 'https://twitter.com/uiarchconf/', 'Active', null, null, null, 'UX standardization,UI Architecture,Design', 'The Howlin'' Wolf 907 S Peters St, New Orleans, LA 70130, United States', 'uiarchconf');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (479, 'EclipseCon', 'https://www.eclipsecon.org/2020', '2020-10-19 00:00:00.000000', '2020-10-22 00:00:00.000000', 'Online Conference', null, null, 'https://www.eclipsecon.org/sites/all/themes/solstice/_themes/solstice_eclipsecon_europe2020/logo.svg', true, null, null, 'EclipseCon 2020 is a virtual event.
A few weeks before the event, registrants will receive an email with information about how to access the event platform and begin using it to connect with the community, set up a personal schedule, and use the platform features to get the most out of the EclipseCon 2020 experience.
There is no registration fee for EclipseCon 2020, although registration is required to attend.
Registration includes Community Day on October 19, 2020, as well as access to the main conference on October 20 - 22.
The conference language is English.
The time zone is Central European Time. The main content is scheduled for 13:00 - 18:00 CET, making it accessible for most of our global community.
', null, null, 'registration@eclipsecon.org', 'https://twitter.com/EclipseFdn', 'Active', 'https://www.facebook.com/eclipse.org', 'https://www.youtube.com/user/EclipseFdn', 'https://www.linkedin.com/company/eclipse-foundation', 'Eclipse', null, 'eclipsecon');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (480, '.NET DeveloperDays', 'https://net.developerdays.pl', '2020-10-19 00:00:00.000000', '2020-10-22 00:00:00.000000', 'Conference', 'Warsaw', 'Poland', 'https://net.developerdays.pl/wp-content/uploads/2019/11/net_dd-300x137.png', false, 'EUR 699', 'EUR 949', '.NET DeveloperDays is the biggest event in Central and Eastern Europe dedicated exclusively to application development on the .NET platform. It is designed for architects, developers, testers and project managers using .NET in their work and to those who want to improve their knowledge and skills in this field. The conference content is 100% English, making it easy for the international audience to attend.', null, 'DATA MASTER ', 'http://data-master.pl/en/homeen/', null, 'Active', 'https://www.facebook.com/DeveloperDays/', null, 'https://www.linkedin.com/company/developer-days/', '.NET', 'EXPO XXI Warsaw
12/14 Prądzyńskiego Str.
01-222 Warsaw, Poland', 'net-developerdays');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (481, 'Global Artificial Intelligence Conference', 'http://www.globalbigdataconference.com/boston/global-artificial-intelligence-conference/event-123.html', '2020-10-20 00:00:00.000000', '2020-10-22 00:00:00.000000', 'Conference', 'Boston', 'USA', 'http://www.globalbigdataconference.com/Content/User/images/logo.png', false, 'USD 489.30', 'USD 2099.33', 'Global Big Data Conference''s vendor agnostic Global Artificial Intelligence(AI) Conference is held on October 20th,  October 21st, & October 22nd 2020 on all industry verticals(Finance, Retail/E-Commerce/M-Commerce, Healthcare/Pharma/BioTech, Energy, Education, Insurance, Manufacturing, Telco, Auto, Hi-Tech, Media, Agriculture, Chemical, Government, Transportation etc.. ). It will be the largest vendor agnostic conference in AI space. The Conference allows practitioners to discuss AI through effective use of various techniques.', 'globalbigdataconference.com', null, null, 'https://twitter.com/bigdataconf', 'Active', 'https://www.facebook.com/globalbigdataconference', 'https://www.youtube.com/user/globalbigdata', 'https://www.linkedin.com/company/globalbigdataconference/', 'Big Data, AL', 'Boston Convention & Exhibition Center , 415 Summer St', 'global-artificial-intelligence-conference');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (482, 'Quantum.Tech', 'https://www.quantumtechcongress.com', '2020-10-23 00:00:00.000000', '2020-10-25 00:00:00.000000', 'Conference', 'Boston', 'USA', 'https://plsadaptive.s3.amazonaws.com/eco/images/builder/fDRAFX4OcVg5crw2UBQaxQXGq2c12nuxXLQRgXyb.png?0.8674521459987237', false, 'TBC', null, 'Using a combination of in-depth, cutting-edge case studies, great networking opportunities, and a broad, comprehensive showcase of the entire supply chain, Quantum.Tech is the global meeting place for the Quantum community. Covering Quantum computing; sensing & metrology; communications & cryptography; hardware, devices and technology applications, Quantum.Tech is the “one stop shop” for understanding the Quantum technology ecosystem.', 'info@alphaevents.com', 'ALPHA EVENTS', 'https://www.alphaevents.com', 'https://twitter.com/QuantumTech_', 'Active', null, null, 'https://www.linkedin.com/showcase/40722733/', 'Quantum', '110 Huntington Ave, Boston, MA 02116, United States', 'quantum-tech');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (483, '.NET Fest', 'https://dotnetfest.com/indexe.html', '2020-10-23 00:00:00.000000', '2020-10-24 00:00:00.000000', 'Conference', 'Kiev', 'Ukraine', 'https://dotnetfest.com/assets/img/dotnet_fest_logo_50.png', false, 'USD 190', 'USD 320', '.NET libraries, frameworks, and platforms used for server-side development and testing
Microservices, monolithic architecture, distributed system design, common architectural patterns
Overview of development and build tools, unit testing toolset
Best practices in development, engineering practices, continuous delivery culture
Clouds and containers, infrastructure as a code, devops tools to support continuous delivery
CLR internals, Runtime Performance & GC; patterns and tools to secure application
', 'info@dotnetfest.com', 'FEST GROUP', 'http://fest.group', 'https://twitter.com/dotNETFest', 'Active', 'https://www.facebook.com/dotnetfest/', null, null, '.NET,Microservices,Clouds,Containers,CLR internals,Runtime Performance,GC', 'Mercure Congress Centre
Vadyma Hetmana St, 6, Kyiv, 02000', 'net-fest');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (484, 'IEEE International Conference on Image Processing', 'https://2020.ieeeicip.org', '2020-10-25 00:00:00.000000', '2020-10-28 00:00:00.000000', 'Conference', 'Abu Dhabi', 'the United Arab Emirates', 'https://2020.ieeeicip.org/wp-content/uploads/sites/148/ICIP2020_Horizontal_2.png', false, 'USD 475', 'USD 775', 'The 27th IEEE International Conference on Image Processing (ICIP 2020) will be held in the Abu Dhabi National Exhibition Center (ADNEC), Abu Dhabi, United Arab Emirates (UAE), on October 25-28, 2020.

ICIP is the world’s largest and most comprehensive technical conference focused on image and video processing and computer vision. ICIP features world-class speakers, tutorials, and industry sessions, and creates an excellent forum to foster innovation and entrepreneurship, and network with the brightest minds in academia and industry that are working in this field. ICIP is the opportunity for industry executives with diverse experience and activity and researchers in distinct yet complementary areas, to discuss the development of emerging and next-generation in terms of technologies, applications, and services thanks to the workshops, panel discussions, and challenge sessions.', null, null, null, 'https://twitter.com/ieeeicip', 'Active', 'https://www.facebook.com/ieeeICIP/', 'https://www.youtube.com/user/IEEEorg', 'https://www.linkedin.com/company/ieee', 'Image Processing ', 'Al Khaleej Al Arabi St - Al RawdahCapital Centre - Abu Dhabi - United Arab Emirates', 'ieee-international-conference-on-image-processing');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (485, 'webinale 2020', 'https://webinale.de/', '2020-12-07 00:00:00.000000', '2020-12-11 00:00:00.000000', 'Conference', 'Berlin', 'Germany', 'https://sandsmedia.com/wp-content/uploads/2020/02/webinale19_Logo_Header_Desktop.png', false, 'EUR 350', 'EUR 1079', 'Accessibility, progressive web apps, modern customer journeys or the latest findings from neuromarketing for increased conversions are just some of the topics presented by the speakers at webinale in a practical way. In addition, they provide insights into fascinating digital trends that you shouldn’t miss! As a crossover platform, the webinale inspires digitally oriented makers from a variety of disciplines – web designers, developers or product owners – and encourages dialogue and exchange of experience.', 'ssuessenberger@webinale.de', 'Software & Support Media GmbH', 'https://sandsmedia.com/en/home/', 'https://twitter.com/webinale', 'Active', 'https://www.facebook.com/webinale', 'https://www.youtube.com/user/webinale', null, 'Online Marketing,UX,Web,Frontend,SEO', null, 'webinale-2020');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (486, 'Java Zone', 'https://2020.javazone.no', '2021-01-20 00:00:00.000000', '2021-01-21 00:00:00.000000', 'Conference', 'Oslo', 'Norway', 'https://2020.javazone.no/logo-sharp.svg', false, 'NOK 6590', null, 'JavaZone – the biggest European community-driven conference for modern developers will be 19 years old in 2020! Don’t miss out on two days of inspiring tech talks, a day of hands-on sessions, mingling, and a great party!

JavaZone is organized by javaBin, the Norwegian Java User Group. Our goal is to organize a community-driven conference for Java developers where they can learn new things, share knowledge, and socialize.

We have been organizing JavaZone since 2001 and have been excited to watch the event grow bigger and better every year. In 2019 we hosted over 3200 participants and 160 speakers across 7 parallel tracks over the course of two days. In addition, we also offered a selection of 11 workshops held on the day before the conference started.', 'javazone@java.no', 'javaBin', 'https://www.java.no/#', 'https://twitter.com/javazone', 'Active', 'https://www.facebook.com/javazoneconference', null, null, 'Java', null, 'java-zone');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (487, 'An Event Apart Orlando', 'https://aneventapart.com/event/orlando-2020', '2021-08-30 00:00:00.000000', '2021-09-01 00:00:00.000000', 'Conference', 'Orlando', 'USA', null, false, 'USA 600', 'USD 1500', 'An Event Apart Orlando is a three-day conference with 17 sessions and an intense focus on digital design, UX, content, code, and more, giving you deep insights into where we are now and where things are going next.', null, 'An Event Apart LLC', 'https://aneventapart.com', 'https://twitter.com/aneventapart', 'Active', 'https://www.facebook.com/An.Event.Apart', 'https://www.youtube.com/AnEventApartLive', null, 'Design,UX', 'Disney’s Contemporary Resort
4600 North World Drive
Lake Buena Vista, FL 32830-8413', 'an-event-apart-orlando');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (488, 'HalfStack Vienna', 'https://halfstackconf.com/vienna/', '2021-09-17 00:00:00.000000', null, 'Conference', 'Vienna', 'Austria', 'https://halfstackconf.com/vienna/assets/images/halfstack-logo.svg', false, 'EUR 200', null, 'An authentic, high value experience for attendees and sponsors focused on UI-centric JavaScript and web development.

The priority for HalfStack is the attendee experience, with great food, drinks, talks, swag, and community. Hosted by London''s longest-lived JavaScript meetup group, HalfStack returns to Vienna for the second time. HalfStack is a UI-centric, one-day single track conference hosted in a relaxed environment.

HalfStack carefully curates talks that inspire and inform the audience in a highly interactive and entertaining manner. An initimate feeling where each attendee has time to meet one another; maximum capacity for Vienna HalfStack is 200 attendees.', 'hello@halfstackconf.com', 'HALFSTACK', 'https://halfstackconf.com', 'https://twitter.com/halfstackconf/', 'Active', 'https://www.facebook.com/halfstackconf/', null, null, 'Front-end,Web,JavaScript,Mobile,IoT', 'Ankersaal, Absberggasse 27, 1100 Vienna', 'halfstack-vienna');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (489, 'JSConf Budapest', 'https://jsconfbp.com', '2021-09-23 00:00:00.000000', '2021-09-24 00:00:00.000000', 'Conference', 'Budapest', 'Hungary ', null, false, 'EUR 311', 'EUR 544', 'We aim to be the JSConf of the region around Eastern-Middle Europe, an area so diverse in culture, people and views. A strictly nonprofit, open-sourced and community driven conference for the community of JavaScript, with the purpose to build and educate about new technologies, ideas and culture.', null, null, null, null, 'Active', null, 'https://www.youtube.com/channel/UCzoVCacndDCfGDf41P-z0iA', null, 'JaveScript', 'Akvarium klub
1051 Budapest, Erzsébet tér 12', 'jsconf-budapest');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (490, 'Dotnetos Conference', 'https://conf.dotnetos.org', '2021-10-13 00:00:00.000000', '2021-10-15 00:00:00.000000', 'Conference', 'Warsaw', 'Poland', 'https://conf.dotnetos.org/images/dotnetos-logo-dark.png', false, 'EUR 179', 'EUR 478', 'The Dotnetos Conference is premium, two-day conference focused on the .NET Core and .NET performance. Top-notch speakers from around the globe and companies like Microsoft or JetBrains. Chance to meet well-known people from .NET community in person!', 'contact@dotnetos.org', null, null, 'https://twitter.com/dotnetosorg', 'Active', 'https://www.facebook.com/dotnetos/', 'https://www.youtube.com/channel/UCC25ZltZWdfjwpTw7XXrybw/', null, '.NET', ' al. Jerozolimskie 65/79, 00-697 Warszawa, Poland', 'dotnetos-conference');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (491, 'Lead Dev San Francisco', 'https://sanfrancisco2020.theleaddeveloper.com', '2021-10-21 00:00:00.000000', '2021-10-22 00:00:00.000000', 'Conference', 'San Francisco, CA.', 'USA', 'https://sanfrancisco2020.theleaddeveloper.com/perch/resources/ldsfonwhite.svg', false, 'USD 1199', 'USD 2399', 'LeadDev Together is a seven-part virtual event series hosted by Anjuan Simmons, who will be joined in each session by a subject specialist co-host. Each session will feature talks and panels from engineering leaders that will ground your knowledge and present new ideas. You’ll then have the opportunity to discuss what you’ve learned in a structured manner – with prompts, exercises, and discussion pieces given to you by our expert hosts.

You’ll attend the sessions with an appetite to change your organisations for the better; and leave with actionable, peer-discussed strategies to effect personal and organisation change.

Check out more about LeadDev Together here', null, null, null, 'https://twitter.com/theleaddev', 'Active', null, 'https://www.youtube.com/channel/UCmM3eCpmWKLJj2PDW_jdGkg', 'https://www.linkedin.com/company/11436053/', 'Devops', 'Mission Bay Conference Center at UCSF
1675 Owens Street | Suite 251 | San Francisco, CA 94143-3008', 'lead-dev-san-francisco');
INSERT INTO public.event (id, name, url, date_from, date_to, type, location_city, location_country, image, free, price_from, price_to, description, contact_info_email, vendor_name, vendor_link, twitter_link, status, facebook_link, youtube_link, linkedin_link, keywords, location_address, slug) VALUES (445, 'JoomlaDay Germany', 'https://www.joomladay.de', '2020-09-26 00:00:00.000000', null, 'Online Conference', null, null, 'https://www.joomladay.de/images/logos/JoomlaDay_Logo.png', false, 'TBC', null, 'JoomlaDay 2020 only online! However, we do not want to completely cancel the JoomlaDay and have decided to host an online JoomlaDay on September 26th, 2020 .

Therefore, our Call for Papers is still open and we look forward to many great contributions from you. We have already received a few great submissions and requests.
', 'hallo@joomladay.de', null, null, 'https://twitter.com/joomlatag?lang=de', 'Active', 'https://www.facebook.com/joomladay/?fref=ts', null, null, 'German,Joomla', '', 'joomladay-germany');